spring:
  application:
    name: account-service

server:
  port: 8090
  
eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true
    
info:
  app:
    description: account-service
    name: account-service
    version: 1.0.0
    
logging:
  level:
    net:
      guides: DEBUG
    org:
      hibernate: ERROR
      springframework:
        web: DEBUG
